name: Publish to npm

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org
          cache: npm

      - run: npm ci
      - run: npm run build

      # Temporary
      - name: Debug OIDC identity
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Workflow Ref: $GITHUB_WORKFLOW_REF"
          echo "Ref: $GITHUB_REF"    

      - run: npm publish --provenance --access public        